name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Chọn phiên bản Python mà bạn muốn sử dụng

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Cài đặt các thư viện từ requirements.txt

    - name: Run tests
      run: |
        python -m pytest  # Sử dụng python -m để chạy pytest
