name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        cd path/to/your/directory  # Chuyển đến thư mục chứa requirements.txt (nếu cần)
        pip install -r requirements.txt  # Cài đặt các thư viện

    - name: Run tests
      run: |
        pytest
